spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/astrobase
    username: postgres
    password:
    driverClassName: org.postgresql.Driver
  flyway:
    baseline-on-migrate: false
    enabled: true
    url: jdbc:postgresql://localhost:5432/astrobase
    schemas: public
    user: postgres
    password:
